# Rime default settings
# encoding: utf-8

config_version: '0.40'

schema_list:
  - schema: zrm
  - schema: zrm_word
  - schema: zrm_phone
  - schema: zrm_dict_xing
  - schema: zrm_dict_desc
  - schema: zrm_dict_jane

switcher:
  caption: 〔方案選單〕
  hotkeys:
    - Control+grave
    - Control+Shift+grave
    - F4
  save_options:
    - full_shape
    - ascii_punct
    - simplification
    - extended_charset
    - zh_hant
    - zh_hans
    - zh_hant_tw
  fold_options: true
  abbreviate_options: true
  option_list_separator: '／'

menu:
  alternative_select_labels: [g,f,d,s,a,b,v,c,x,z,G,F,D,S,A,B,V,C,X,Z]  # 修改候選標籤
  page_size: 20  #選單每䈎顯示個數
  #alternative_select_labels: [G,F,D,S,A]  # 修改候選標籤
  #page_size: 5  #選單每䈎顯示個數
  
punctuator:
  full_shape:
    __include: punctuation:/full_shape
  half_shape:
    __include: punctuation:/half_shape

key_binder:
  bindings:
    __patch:
      - key_bindings:/emacs_editing
      - key_bindings:/move_by_word_with_tab
      - key_bindings:/paging_with_minus_equal
      - key_bindings:/paging_with_comma_period
      - key_bindings:/numbered_mode_switch



ascii_composer:
  good_old_caps_lock: true
  switch_key:
    Shift_L: noop
    Shift_R: noop
    Control_L: noop
    Control_R: noop
    Caps_Lock: noop
    Eisu_toggle: clear
